version: '3.7'
services:
  client:
    image: anilen_authenticate_client
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anilen_authenticate_client
    environment:
      - BASE_URL= http://rado.invest.lan/login
    ports:
      - '8001:80'
    restart: always

networks:
  default:
    name: nginx_configuration_default