version: '3.7'
services:
  client:
    image: anilen_authenticate_client
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anilen_authenticate_client
    ports:
      - '8001:80'
    restart: always
    environment:
      - APP_STAGE=development

networks:
  default:
    name: nginx_configuration_default